apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: locking-nfs-client-provisioner
  namespace: storage
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch", "delete", "create", "patch"]